print("Hello, All !!")
print()
myname=input("Enter your Name:")
print("How you Doin?,",myname)
print()
num=input("Enter a Number:")
print("You have entered ",num)
print("It's Double is ", num*2)
print("It's 10 percent is ", float(num)*0.1)
print()
print("Thank you !")
